// <auto-generated />
namespace Cms.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class IntialDb_Db1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IntialDb_Db1));
        
        string IMigrationMetadata.Id
        {
            get { return "201804210208119_IntialDb_Db1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
